=== lkx007/AlertingSP/emc-mss-srmhealth-alerts/trunk/blocks/collect/templates/property-tagging-filter/conf/property-tagging-filter-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter"
	elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation>
            The property tagging filter configuration file. Copyright
            2008 Watch4Net Solutions. All rights reserved.
        </xsd:documentation>
    </xsd:annotation>

	<xsd:element name="property-tagging-filter-config">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="refresh" type="refresh-type" maxOccurs="1" minOccurs="1" />
				<xsd:element name="files" maxOccurs="1" minOccurs="1" type="files-type" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="refresh-type">
		<xsd:simpleContent>
			<xsd:extension base="xsd:nonNegativeInteger">
				<xsd:attribute name="unit" type="refresh-unit-enum" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:simpleType name="refresh-unit-enum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="days" />
			<xsd:enumeration value="hours" />
			<xsd:enumeration value="minutes" />
			<xsd:enumeration value="seconds" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="files-type">
		<xsd:sequence>
			<xsd:element name="text-file" maxOccurs="unbounded" minOccurs="0" type="text-file-type" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="text-file-type">
		<xsd:sequence>
			<xsd:element name="accessor" type="accessor-type" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="field-separator" type="string1" maxOccurs="1" minOccurs="1" />
			<xsd:element name="field-quoting" maxOccurs="1" minOccurs="0" type="char" />
			<xsd:element name="default-symbol" type="string1" maxOccurs="1" minOccurs="1" />
			<xsd:element name="null-symbol" type="string1" maxOccurs="1" minOccurs="0" />
			<xsd:element name="property-insertion" maxOccurs="1" minOccurs="0" >
				<xsd:complexType>
					<xsd:attribute name="start" use="required" />
					<xsd:attribute name="end" use="required" />
				</xsd:complexType>					
			</xsd:element>
			<xsd:element name="key-properties" type="key-properties-type" maxOccurs="1" minOccurs="1" />
			<xsd:element name="new-properties" type="new-properties-type" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="path" type="xsd:string" use="required" />
		<xsd:attribute name="encoding" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="accessor-type">
		<xsd:sequence>
			<xsd:element name="parameter" type="parameter-type"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="accessor-class" type="string1"  use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="parameter-type">
		<xsd:simpleContent>
			<xsd:extension base="string1">
				<xsd:attribute name="name" type="string1"  use="required" />	
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="key-properties-type">
		<xsd:sequence>
			<xsd:element name="key-property" maxOccurs="unbounded" minOccurs="0">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="property-name-type">
							<xsd:attribute name="string-type" type="string-type-enum" default="string" />
							<xsd:attribute name="delete-after-use" type="xsd:boolean" default="false" />
							<xsd:attribute name="decoder" type="xsd:string" use="optional"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="new-properties-type">
		<xsd:sequence>
			<xsd:element name="new-property" maxOccurs="unbounded" minOccurs="1">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="property-name-type">
						  <xsd:attribute name="encoder" type="xsd:string" use="optional"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="property-name-type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value=".+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="string-type-enum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="regex" />
			<xsd:enumeration value="sqlpattern" />
			<xsd:enumeration value="range" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="char">
		<xsd:restriction base="xsd:string">
			<xsd:length value="1" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="string1">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== lkx007/AlertingSP/brocade-fc-switch/branch/3.0/blocks/collect/templates/property-tagging-filter/conf/PTF-Group-Tagging.xml
<?xml version="1.0" encoding="UTF-8"?>
<property-tagging-filter-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter" xsi:schemaLocation="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter  property-tagging-filter-config.xsd">
        <refresh unit="minutes">0</refresh>
        <files>
		<!--To group the devices based on their type-->
		<text-file path="conf/user-defined-groups.csv" encoding="UTF-8">
			<field-separator>,</field-separator>
			<field-quoting>"</field-quoting>

			<default-symbol>**</default-symbol>

			<null-symbol>@@</null-symbol>

			<property-insertion start="${" end="}" />
			
			<key-properties>
				<key-property delete-after-use="false" string-type="regex">devtype</key-property>
				<key-property delete-after-use="false" string-type="regex">device</key-property>
			</key-properties>
			<!-- new nodegrp property -->
			<new-properties>
				<new-property>nodegrp</new-property>
			</new-properties>
		</text-file>
		
        </files>
</property-tagging-filter-config>

=== lkx007/AlertingSP/emc-centera/branch/1.0/blocks/collect/templates/property-tagging-filter/conf/property-tagging-filter-centera.xml
<?xml version="1.0" encoding="UTF-8"?>
<property-tagging-filter-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter  property-tagging-filter-config.xsd" xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter">
	<refresh unit="minutes">0</refresh>
	<files>
		<text-file path="conf/rename_grp.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">[datagrp][serialnb][parttype][part][name]</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<property-insertion start="[" end="]" />
			<key-properties>
			</key-properties>
			<new-properties>
				<new-property>RV_Variable</new-property>      
			</new-properties>
		</text-file>
	</files>
</property-tagging-filter-config>

=== lkx007/AlertingSP/emc-vnx/branch/1.3u1/blocks/collect/templates/property-tagging-filter/conf/property-tagging-filter-vnxblock.xml
<?xml version="1.0" encoding="UTF-8"?>
<property-tagging-filter-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter" xsi:schemaLocation="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter  property-tagging-filter-config.xsd">
	<refresh unit="minutes">0</refresh>
	<files>
		<text-file path="conf/vnx_models.csv">
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="regex">model</key-property>
			</key-properties>
			<new-properties>
				<new-property>maxdisk</new-property>
				<new-property>maxhost</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/hd_rpm.csv">
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="regex">partmdl</key-property>
			</key-properties>
			<new-properties>
				<new-property>diskrpm</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/hd_latency.csv">
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="string">diskrpm</key-property>
			</key-properties>
			<new-properties>
				<new-property>disklate</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/hd_factors.csv">
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="string">diskrpm</key-property>
				<key-property delete-after-use="false" string-type="string">disktype</key-property>
			</key-properties>
			<new-properties>
				<new-property>partmax</new-property>
				<new-property>seektime</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/disk_cost_per_gigabyte.csv">
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="regex">model</key-property>
				<key-property delete-after-use="false" string-type="string">dgraid</key-property>
				<key-property delete-after-use="false" string-type="string">tiername</key-property>
			</key-properties>
			<new-properties>
				<new-property>cost</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/business_unit.csv">
			<field-separator>,</field-separator>
			<field-quoting>"</field-quoting>
			<default-symbol>**</default-symbol>
			<null-symbol>@@</null-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="string">device</key-property>
				<key-property delete-after-use="false" string-type="regex">part</key-property>
			</key-properties>
			<new-properties>
				<new-property>bunit</new-property>
				<new-property>appname</new-property>
				<new-property>appowner</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/moduletotier.csv">
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="string">module</key-property>
			</key-properties>
			<new-properties>
				<new-property>tiername</new-property>
			</new-properties>
		</text-file>
	</files>
</property-tagging-filter-config>

=== lkx007/AlertingSP/emc-vmax/branch/2.1/blocks/collect/templates/property-tagging-filter/conf/ptf-vmax1.xml
<?xml version="1.0" encoding="UTF-8"?>
<property-tagging-filter-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter  property-tagging-filter-config.xsd" xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter">
	<refresh unit="minutes">60</refresh>
	<files>
		<text-file path="conf/ptf-vmax-dgstype.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">LUN,@@,Thick</parameter>
				<parameter name="line">METALUN,@@,Thick</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<null-symbol>@@</null-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="regex">parttype</key-property>
				<key-property delete-after-use="false" string-type="regex">dgstype</key-property>
			</key-properties>
			<new-properties>
				<new-property>dgstype</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/ptf-vmax-unprotected.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">LUN,Unprotected,0</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<null-symbol>@@</null-symbol>
			<key-properties>
				<key-property delete-after-use="false" string-type="regex">parttype</key-property>
				<key-property delete-after-use="false" string-type="regex">config</key-property>
			</key-properties>
			<new-properties>
				<new-property>roc1</new-property>
			</new-properties>
		</text-file>
	</files>
</property-tagging-filter-config>

=== lkx007/AlertingSP/emc-isilon/trunk/blocks/collect/templates/property-tagging-filter/conf/ptf-isilon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
* Copyright (c) 2014 EMC Corporation
* All Rights Reserved
*
* This software contains the intellectual property of EMC Corporation
* or is licensed to EMC Corporation from third parties.  Use of this
* software and the intellectual property contained therein is expressly
* limited to the terms and conditions of the License Agreement under which
* it is provided by or on behalf of EMC.
-->
<property-tagging-filter-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter" xsi:schemaLocation="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter  property-tagging-filter-config.xsd">
	<refresh unit="minutes">60</refresh>
	<files>
		<!-- sets parttype & !part after ICF -->
		<text-file path="conf/overrideHDDCapacity.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">FileSystem,HDDCapacity,Disk,</parameter>
				<parameter name="line">FileSystem,HDDUsedCapacity,Disk,</parameter>
				<parameter name="line">FileSystem,HDDFreeCapacity,Disk,</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<property-insertion start="[" end="]" />
			<key-properties>
				<key-property delete-after-use="false" string-type="string">parttype</key-property>
				<key-property delete-after-use="false" string-type="string">name</key-property>
			</key-properties>
			<new-properties>
				<new-property>parttype</new-property>      
				<new-property>part</new-property>      
			</new-properties>
		</text-file>
		<text-file path="conf/rename_variableid_isilon.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">[source][serialnb][nodeid][parttype][part][name]</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<property-insertion start="[" end="]" />
			<key-properties>
			</key-properties>
			<new-properties>
				<new-property>RV_Variable</new-property>      
			</new-properties>
		</text-file>
	</files>
</property-tagging-filter-config>

=== lkx007/AlertingSP/emc-vnx/branch/3.0/blocks/collect/templates/property-tagging-filter/conf/property-tagging-filter-vnxfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
* Copyright (c) 2013 EMC Corporation
* All Rights Reserved
*
* This software contains the intellectual property of EMC Corporation
* or is licensed to EMC Corporation from third parties.  Use of this
* software and the intellectual property contained therein is expressly
* limited to the terms and conditions of the License Agreement under which
* it is provided by or on behalf of EMC.
-->
<property-tagging-filter-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter" xsi:schemaLocation="http://www.watch4net.com/APG/Filter/PropertyTaggingFilter  property-tagging-filter-config.xsd">
	<refresh unit="minutes">0</refresh>
	<files>
		<text-file path="conf/luntagid.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">VNXFile-Collector,Disk,[storsn]_0[storlun]</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<property-insertion start="[" end="]" />
			<key-properties>
				<key-property delete-after-use="false" string-type="string">source</key-property>
				<key-property delete-after-use="false" string-type="string">parttype</key-property>
			</key-properties>
			<new-properties>
				<new-property>luntagid</new-property>
			</new-properties>
		</text-file>
		<text-file path="conf/rename_variableid.csv">
			<accessor accessor-class="StaticAccessor">
				<parameter name="field-separator">,</parameter>
				<parameter name="field-quoting">"</parameter>
				<parameter name="line">[datagrp][serialnb][parttype][moverid][partid][ifname][volumeid][qpath][partsn][name]</parameter>
			</accessor>
			<field-separator>,</field-separator>
			<default-symbol>**</default-symbol>
			<property-insertion start="[" end="]" />
			<key-properties>
			</key-properties>
			<new-properties>
				<new-property>RV_Variable</new-property>
			</new-properties>
		</text-file>
	</files>
</property-tagging-filter-config>
